version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:

# Exercise: Infrastructure creation
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: Create Cloudformation Stack # run the command
            command: |
              aws cloudformation deploy \
                --template-file infra.yml \
                --stack-name mystack \
                --region us-east-1


# Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["22:76:17:dc:63:16:05:88:cc:d4:35:69:e9:51:f3:12"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: ls-la root
          command: |
            ls -la ~/.ssh/id_rsa.pub
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt playbook-config.yml 




# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infrastructure
      - configure_infrastructure
      